const ActionTypes = {
  FETCH_APP_DATA_SUCCESS: "FETCH_APP_DATA_SUCCESS",
  FETCH_APP_DATA_ERROR: "FETCH_APP_DATA_ERROR",
  ADD_UPDATE_APP_DATA: "UPDATE_APP_DATA",
  SUBTRACT_UPDATE_APP_DATA: "SUBTRACT_UPDATE_APP_DATA"
};

export default ActionTypes;
